# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_log(object):
    def setupUi(self, MainWindow_log):
        MainWindow_log.setObjectName("MainWindow_log")
        MainWindow_log.resize(250, 250)
        MainWindow_log.setMinimumSize(QtCore.QSize(250, 250))
        MainWindow_log.setMaximumSize(QtCore.QSize(250, 250))
        self.centralwidget = QtWidgets.QWidget(MainWindow_log)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.verticalLayout.addWidget(self.login_label)
        self.login_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.login_lineEdit.setFont(font)
        self.login_lineEdit.setText("")
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.verticalLayout.addWidget(self.login_lineEdit)
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.enter.setFont(font)
        self.enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter.setObjectName("enter")
        self.verticalLayout.addWidget(self.enter)
        self.registration = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.registration.setFont(font)
        self.registration.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registration.setObjectName("registration")
        self.verticalLayout.addWidget(self.registration)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow_log.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_log)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_log.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_log)
        self.statusbar.setObjectName("statusbar")
        MainWindow_log.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_log)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_log)

    def retranslateUi(self, MainWindow_log):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_log.setWindowTitle(_translate("MainWindow_log", "MainWindow"))
        self.login_label.setText(_translate("MainWindow_log", "Логин:"))
        self.password_label.setText(_translate("MainWindow_log", "Пароль:"))
        self.enter.setText(_translate("MainWindow_log", "Войти"))
        self.registration.setText(_translate("MainWindow_log", "Регистрация"))
