# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_main(object):
    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.resize(500, 600)
        MainWindow_main.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow_main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, 350)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setText("")
        self.info.setObjectName("info")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.info)
        self.dateOfbirth = QtWidgets.QLabel(self.centralwidget)
        self.dateOfbirth.setText("")
        self.dateOfbirth.setObjectName("dateOfbirth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateOfbirth)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.city = QtWidgets.QLabel(self.centralwidget)
        self.city.setText("")
        self.city.setObjectName("city")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.city)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow_main", "Моя страница"))
        self.pushButton_2.setText(_translate("MainWindow_main", "Друзья"))
        self.pushButton_3.setText(_translate("MainWindow_main", "Сообщения"))
        self.pushButton_4.setText(_translate("MainWindow_main", "Выход"))
        self.label_4.setText(_translate("MainWindow_main", "Город:"))
        self.label_3.setText(_translate("MainWindow_main", "Дата рождения:"))
        self.label_2.setText(_translate("MainWindow_main", "Информация:"))
