# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_main(object):
    def setupUi(self, MainWindow_main):
        MainWindow_main.setObjectName("MainWindow_main")
        MainWindow_main.resize(700, 800)
        MainWindow_main.setMinimumSize(QtCore.QSize(700, 800))
        MainWindow_main.setMaximumSize(QtCore.QSize(700, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow_main)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 681, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.my_page_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.my_page_btn.setFont(font)
        self.my_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.my_page_btn.setObjectName("my_page_btn")
        self.horizontalLayout.addWidget(self.my_page_btn)
        self.friends_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.friends_btn.setFont(font)
        self.friends_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.friends_btn.setObjectName("friends_btn")
        self.horizontalLayout.addWidget(self.friends_btn)
        self.message_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.message_btn.setFont(font)
        self.message_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.message_btn.setObjectName("message_btn")
        self.horizontalLayout.addWidget(self.message_btn)
        self.exit_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 681, 691))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateOfbirth = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateOfbirth.setFont(font)
        self.dateOfbirth.setText("")
        self.dateOfbirth.setObjectName("dateOfbirth")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateOfbirth)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.city = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.city.setFont(font)
        self.city.setText("")
        self.city.setObjectName("city")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.city)
        self.add_friend_page_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.add_friend_page_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_friend_page_btn.setFont(font)
        self.add_friend_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_friend_page_btn.setObjectName("add_friend_page_btn")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.add_friend_page_btn)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 681, 581))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.formLayoutWidget_2.setFont(font)
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.search2_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.search2_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search2_btn.setFont(font)
        self.search2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search2_btn.setObjectName("search2_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.search2_btn)
        self.my_friend_tableWidget = QtWidgets.QTableWidget(self.formLayoutWidget_2)
        self.my_friend_tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.my_friend_tableWidget.setFont(font)
        self.my_friend_tableWidget.setObjectName("my_friend_tableWidget")
        self.my_friend_tableWidget.setColumnCount(4)
        self.my_friend_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.my_friend_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_friend_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_friend_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.my_friend_tableWidget.setHorizontalHeaderItem(3, item)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.my_friend_tableWidget)
        self.del_friend_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.del_friend_btn.setEnabled(True)
        self.del_friend_btn.setObjectName("del_friend_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.del_friend_btn)
        self.go_to_page_btn_3 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.go_to_page_btn_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.go_to_page_btn_3.setFont(font)
        self.go_to_page_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_page_btn_3.setObjectName("go_to_page_btn_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.go_to_page_btn_3)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.search1_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.search1_lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search1_lineEdit.setFont(font)
        self.search1_lineEdit.setObjectName("search1_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.search1_lineEdit)
        self.search1_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.search1_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search1_btn.setFont(font)
        self.search1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search1_btn.setObjectName("search1_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.search1_btn)
        self.search1_tableWidget = QtWidgets.QTableWidget(self.formLayoutWidget_2)
        self.search1_tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search1_tableWidget.setFont(font)
        self.search1_tableWidget.setObjectName("search1_tableWidget")
        self.search1_tableWidget.setColumnCount(4)
        self.search1_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search1_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search1_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search1_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search1_tableWidget.setHorizontalHeaderItem(3, item)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.search1_tableWidget)
        self.add_friend_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.add_friend_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_friend_btn.setFont(font)
        self.add_friend_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_friend_btn.setObjectName("add_friend_btn")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.add_friend_btn)
        self.go_to_page_btn_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.go_to_page_btn_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.go_to_page_btn_2.setFont(font)
        self.go_to_page_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_page_btn_2.setObjectName("go_to_page_btn_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.go_to_page_btn_2)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.subs_tableWidget = QtWidgets.QTableWidget(self.formLayoutWidget_2)
        self.subs_tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subs_tableWidget.setFont(font)
        self.subs_tableWidget.setObjectName("subs_tableWidget")
        self.subs_tableWidget.setColumnCount(4)
        self.subs_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.subs_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subs_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subs_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subs_tableWidget.setHorizontalHeaderItem(3, item)
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.subs_tableWidget)
        self.add_friend_btn_2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.add_friend_btn_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_friend_btn_2.setFont(font)
        self.add_friend_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_friend_btn_2.setObjectName("add_friend_btn_2")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.add_friend_btn_2)
        self.go_to_page_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.go_to_page_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.go_to_page_btn.setFont(font)
        self.go_to_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_to_page_btn.setObjectName("go_to_page_btn")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.go_to_page_btn)
        self.search2_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.search2_lineEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.search2_lineEdit.setFont(font)
        self.search2_lineEdit.setObjectName("search2_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.search2_lineEdit)
        MainWindow_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_main)
        self.statusbar.setObjectName("statusbar")
        MainWindow_main.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_main)

    def retranslateUi(self, MainWindow_main):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_main.setWindowTitle(_translate("MainWindow_main", "MainWindow"))
        self.my_page_btn.setText(_translate("MainWindow_main", "Моя страница"))
        self.friends_btn.setText(_translate("MainWindow_main", "Друзья"))
        self.message_btn.setText(_translate("MainWindow_main", "Сообщения"))
        self.exit_btn.setText(_translate("MainWindow_main", "Выход"))
        self.label_3.setText(_translate("MainWindow_main", "Дата рождения:"))
        self.label_4.setText(_translate("MainWindow_main", "Город:"))
        self.add_friend_page_btn.setText(_translate("MainWindow_main", "Добавить в друзья"))
        self.label.setText(_translate("MainWindow_main", "Мои друзья:"))
        self.search2_btn.setText(_translate("MainWindow_main", "Поиск"))
        item = self.my_friend_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_main", "id"))
        item = self.my_friend_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_main", "Имя"))
        item = self.my_friend_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_main", "Фамилия"))
        item = self.my_friend_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_main", "Отчество"))
        self.del_friend_btn.setText(_translate("MainWindow_main", "Удалить друга"))
        self.go_to_page_btn_3.setText(_translate("MainWindow_main", "Посетить друга"))
        self.label_2.setText(_translate("MainWindow_main", "Поиск пользователей:"))
        self.search1_btn.setText(_translate("MainWindow_main", "Поиск"))
        item = self.search1_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_main", "id"))
        item = self.search1_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_main", "Имя"))
        item = self.search1_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_main", "Фамилия"))
        item = self.search1_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_main", "Отчество"))
        self.add_friend_btn.setText(_translate("MainWindow_main", "Подписаться"))
        self.go_to_page_btn_2.setText(_translate("MainWindow_main", "Посетить пользовтеля"))
        self.label_5.setText(_translate("MainWindow_main", "Подписчики:"))
        item = self.subs_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_main", "id"))
        item = self.subs_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_main", "Имя"))
        item = self.subs_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_main", "Фамилия"))
        item = self.subs_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_main", "Отчество"))
        self.add_friend_btn_2.setText(_translate("MainWindow_main", "Добавить в друзья"))
        self.go_to_page_btn.setText(_translate("MainWindow_main", "Посетить пользовтеля"))
