# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_reg(object):
    def setupUi(self, MainWindow_reg):
        MainWindow_reg.setObjectName("MainWindow_reg")
        MainWindow_reg.resize(300, 460)
        MainWindow_reg.setMinimumSize(QtCore.QSize(300, 460))
        MainWindow_reg.setMaximumSize(QtCore.QSize(300, 460))
        self.centralwidget = QtWidgets.QWidget(MainWindow_reg)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setText("")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout.addWidget(self.name_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.surname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.surname_lineEdit.setFont(font)
        self.surname_lineEdit.setObjectName("surname_lineEdit")
        self.verticalLayout.addWidget(self.surname_lineEdit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.patronymic_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.patronymic_lineEdit.setFont(font)
        self.patronymic_lineEdit.setObjectName("patronymic_lineEdit")
        self.verticalLayout.addWidget(self.patronymic_lineEdit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.mail_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mail_lineEdit.setFont(font)
        self.mail_lineEdit.setObjectName("mail_lineEdit")
        self.verticalLayout.addWidget(self.mail_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.password_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.datebirth_dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.datebirth_dateEdit.setFont(font)
        self.datebirth_dateEdit.setObjectName("datebirth_dateEdit")
        self.verticalLayout.addWidget(self.datebirth_dateEdit)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.city_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.city_lineEdit.setFont(font)
        self.city_lineEdit.setObjectName("city_lineEdit")
        self.verticalLayout.addWidget(self.city_lineEdit)
        self.reg = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reg.setFont(font)
        self.reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg.setObjectName("reg")
        self.verticalLayout.addWidget(self.reg)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow_reg.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_reg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_reg.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_reg)
        self.statusbar.setObjectName("statusbar")
        MainWindow_reg.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_reg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_reg)

    def retranslateUi(self, MainWindow_reg):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_reg.setWindowTitle(_translate("MainWindow_reg", "MainWindow"))
        self.label.setText(_translate("MainWindow_reg", "Имя:"))
        self.label_2.setText(_translate("MainWindow_reg", "Фамилия:"))
        self.label_3.setText(_translate("MainWindow_reg", "Отчество:"))
        self.label_4.setText(_translate("MainWindow_reg", "Логин:"))
        self.label_5.setText(_translate("MainWindow_reg", "Пароль:"))
        self.label_6.setText(_translate("MainWindow_reg", "Дата рождения:"))
        self.label_7.setText(_translate("MainWindow_reg", "Город:"))
        self.reg.setText(_translate("MainWindow_reg", "Регистрация"))
